# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b2f11fb11aea31c709bbfe26d6fd7fd679a10044da01e06283c16d988efe9a20062dffc07b4a8926273b0dbfe9d7557ef7150b5d53944828df2d6dfb58c4ba9

test:
  secret_key_base: c60cb51df83cd4dbf39a9d30bf6e5d66440434c755576e167991b91cc5d5832607a391f17cd9c5373c2af9cd389d624e0789f2e5ee56ad580a2ce25438030dfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
